### ISSUE TITLE
Ansatz FinanzenExport

### ISSUE THREAD

**Issue by michael-dev** [Ref-IT/ProtokollCleaner#9]
Warum können die Beschlüsse für das FinanzenTool nicht einfach aus der WikiSeite mit der Beschlussliste exportiert werden?

**Comment by lu-kors** [comment]
Die Überlegung war ja zusätzlich auch die Beschlussliste automatisch zu generierenmichael-dev <notifications@github.com> schrieb:
Warum können die Beschlüsse für das FinanzenTool nicht einfach aus der WikiSeite mit der Beschlussliste exportiert werden?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ref-IT/ProtokollCleaner","title":"Ref-IT/ProtokollCleaner","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Ref-IT/ProtokollCleaner"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Ansatz FinanzenExport (#9)"}],"action":{"name":"View Issue","url":"https://github.com/Ref-IT/ProtokollCleaner/issues/9"}}}
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Squeaky Mail gesendet.

**Comment by targetingsnake** [comment]
@michael-dev  Das Tool liest auch die Beschlussliste, siehe Zeile 184 ff, und crawlt sich aus der Liste dann auch die Beschlüsse.
